= AssetTracker
Paweł Truong
:toc:
:toclevels: 4

:repo-url: https://github.com/paweltruong/AssetTracker
:license-url: https://opensource.org/licenses/MIT
:dotnet-version: 8.0


image:https://img.shields.io/badge/License-MIT-yellow.svg[License: MIT,link={license-url}]
image:https://img.shields.io/badge/.NET-{dotnet-version}-purple.svg[.NET,link=https://dotnet.microsoft.com]



From idea to final product

== Introduction

If you are using Humble Bundle you often wonder how many products from a bundle you already have. Those products that you already have might be games, books, software or other digital assets. 
You buy them often on different platforms like Steam, GOG, Epic Games Store, Amazon Kindle, Audible or others. So it is hard to track what you already have and what you still need to buy to complete your collection. This is where AssetTracker comes into play.

== Stage 1 Proof of Concept

I had some idea what features AssetTracker should have, but definetily problem is to be discoverd there is no expert to consult in this matter. So I decided to build a simple proof of concept application to validate my idea. I had to reasearch what technologies I can use to build this application, what is really possible.

=== The reasearch

Using my own experience and other tools like AI chatbots, google etc. I tried to find out what features and use cases or essential for me and what would be some of the technical problems.

*Features:*

* Importing asset data from multiple sources like Humble Bundle, Steam, GOG, Epic Games Store, Prime Gaming, FAB, Unity Asset Store, Cosmos from Leartes, Itch.io, Synty Store etc.
* Tracking owned assets and ability to aggregate them
* Tracking wishlisted assets

*Problematic areas:*

* Duplicates handling - sometimes I could have same products on different store fe. Unity Asset Store and Synty Store
* Different asset meta data formats depending on API or data available on the websites for scrapping
* Different import approaches Steam provides API, Humble Bundle provides API but only for partners other types would require scraping the data from web, this could be problematic if website structure changes, and to acces your assets you have to be logged in, so scrapping would require handling authentication cookies etc. There are solutions for this but this is strictly related to the final technology or infrastructure used for the application.

=== The Minimal Viable Product and Happy Path

Using the reasearch above I decided to build a simple proof of concept application that would allow me to import my Steam game library.

First I've focused on the happy path and used Vibe coding approach. This would give me quick feedback if my idea is valid and if I can proceed with further development.

*Observations:*

* UX - I have to store data used for importing assets, like authentication cookies for web scrapping, API keys etc. It is very inconvenient to provide this data every time I want to import my assets. So I have to build some kind of user profile management.
* Security - storing sensitive data like authentication cookies or API keys requires proper security measures. I have to make sure this data is stored securely or not in plain text at least.
* UX - there should be features for managing imported assets (sorting, filtering, tagging etc.)
 